GET https://example.com/comments/1 HTTP/1.1

###

GET https://example.com/topics/1 HTTP/1.1

###

POST http://localhost:5000/quotes HTTP/1.1
content-type: application/json

{
    "species": "Dog",
    "name": "Fido",
    "gender": "Male",
    "breedType": "Poodle (Toy)",
    "breed": "Pedigree",
    "age": "12",
    "spayed": "true",
    "postcode": "PO51EQ",
    "email": "test@email.com",
    "coverLength": "4"
}